Repository SCCSEAOT/NonCode-Contribution, pull requests merged in 2022-10, with the labels that each got.

#2 leadership
  Keynotes on Leadership.pdf
Labels: Hacktoberfest Accepted

#3 Create Collaboration_in_business.pdf
  Business_and_managemenet_writing/Collaboration_in_business.pdf
Labels: Hacktoberfest Accepted

#6 Create BGMI.txt
  Tunir/BGMI.txt
Labels: Hacktoberfest, Hacktoberfest Accepted

#7 Create EHUNT.txt
  Tunir/EHUNT.txt
Labels: Hacktoberfest, Hacktoberfest Accepted

#5 Create business_strategy.pdf
  Business_and_managemenet_writing/Business_strategy.pdf
Labels: enhancement, Hacktoberfest, Hacktoberfest Accepted

#8 banner
  Poster/readme.md
  banner (7).png
Labels: Hacktoberfest, Hacktoberfest Accepted

#9 bnner
  STRIDE  DAY 5 (3).png
Labels: Hacktoberfest, Hacktoberfest Accepted

#11 poster.png
  STRIDE  DAY 5 (1).png
  STRIDE  DAY 5 (2).png
Labels: Hacktoberfest, Hacktoberfest Accepted

#15 Update README.md
  Business_and_managemenet_writing/Collaboration_in_business.pdf
  README.md
Labels: Hacktoberfest, Hacktoberfest Accepted

#14 Fixed typos #1
  README.md
Labels: Hacktoberfest, Hacktoberfest Accepted

#17 Update README.md
  Business_and_managemenet_writing/Funds_raising_in_Business.pdf
  README.md
Labels: documentation, Hacktoberfest Accepted

#16 Article on Augmented Reality
  Augmented Reality
Labels: Hacktoberfest, Hacktoberfest Accepted
